field_mappings:
  系统单号: Order_ID                                     
  参考号: Reference_ID                                   
  状态: Order_Status                                     
  配送状态: Item_Status                                  
  上次更新日期: Last_Update_Datetime                     
  发货服务级别: Ship_Service_Level                       
  平台: Fulfillment_Channel                      
  店铺: Store                           
  站点: Sales_Channel                            
  是否企业订单: Is_Business_Order                       
  采购订单号: Purchase_Order_Number                     
  客服备注: Note                                        
  买家备注: Remark_From_Buyer                           
  订单来源: Order_Source                                
  订单类型: Shipment_Method                    
  标签: Tags                     
  订购时间: Purchase_Datetime                           
  付款时间: Payment_Datetime                            
  发货时限: Ship_Deadline_Datetime                      
  发货时间: Ship_Datetime                               
  标发时间: Estimated_Ship_Out_Datetime                 
  不发货时间: Do_Not_Ship_Datetime                      
  指定配送时间: Scheduled_Delivery_Datetime             
  订单完成时间: Order_Complete_Datetime                 
  品名: Product_Name                                    
  MSKU: MSKU                                            
  商品Id: Product_ID                                    
  价格标识: Price_Designation                           
  建议签名确认: Signature_Confirmation_Recommended      
  订单商品ID: Order_Item_ID                             
  商品标题: Product_Title              
  69码: 69_Code                                       
  规格名称: Variation_Name                              
  变体属性: Variation_Attribute                         
  原始价格: Original_Price                              
  成交价格: Deal_Price                                  
  单价: Unit_Price                      
  数量: Quantity                                        
  件数: Number_Of_Pieces                                
  退货数量: Return_Quantity                             
  商品金额: Item_Price                                  
  服务费: Service_Fee                                   
  实付金额: Products_Price_Paid_By_Buyer                
  信用卡折扣: Credit_Card_Discount_Total                
  金币抵扣: Coin_Offset                                 
  退货运费: Reverse_Shipping_Fee                        
  商品客付运费: Shipping_Price                          
  商品客付税费: Item_Tax                                
  运费税: Shipping_Tax                                  
  礼品包装价格: Gift_Wrap_Price                         
  礼品包装税: Gift_Wrap_Tax                             
  商品小费: Product_Tip                                 
  商品折扣: Item_Promotion_Discount                     
  店铺折扣: Store_Discount                              
  店铺优惠券: Store_Voucher                             
  平台优惠券: Platform_Voucher                          
  平台折扣: Platform_Discount                           
  运费折扣: Ship_Promotion_Discount                     
  商品交易费: Transaction_Fee                           
  促销代码: Promotion_Ids                               
  商品平台补贴: Product_Platform_Subsidy                
  商品平台其它费: Product_Platform_Other_Fees           
  商品出库成本: Product_Outbound_Cost                   
  商品物流运费币种: Product_Shipping_Cost_Currency      
  商品物流运费: Product_Shipping_Cost                   
  商品备注: Product_Notes                               
  商品负责人: Product_Manager                           
  商品标签: Product_Tags                                
  买家支付运费: Buyer_Paid_Shipping_Fee                 
  平台组合折扣: Platform_Bundle_Discount                
  卖家组合折扣: Seller_Bundle_Discount                  
  最早获取面单时间: Earliest_Label_Acquisition_Datetime 
  客选物流: Customer_Selected_Logistics                  
  发货仓库: Shipping_Warehouse                          
  物流方式: Logistics_Method                            
  运单号: Tracking_Number                               
  跟踪号: Tracking_Number_External                      
  标发号: Labeled_Number                                
  税号类型: Tax_ID_Type                                 
  寄件税号: Sender_Tax_ID                               
  COD订单: COD_Order                                    
  预估重量: Estimated_Weight_g                       
  预估尺寸长: Estimated_Length_cm                   
  预估尺寸宽: Estimated_Width_cm                    
  预估尺寸高: Estimated_Height_cm                   
  预估计费重: Estimated_Billable_Weight_g            
  预估运费: Estimated_Shipping_Cost_CNY            
  sku重量: SKU_Total_Weight                                  
  包裹实重: Order_Total_Weight_g                  
  包裹尺寸长: Package_Length_cm                     
  包裹尺寸宽: Package_Width_cm                      
  包裹尺寸高: Package_Height_cm                     
  实际计费重: Actual_Billable_Weight_g               
  物流运费币种: Shipping_Cost_Currency                  
  物流运费: Shipping_Cost                               
  订单币种: Currency                                    
  订单总金额: Total_Amount                              
  订单出库成本: Outbound_Cost_CNY                   
  预估毛利润: Estimated_Gross_Profit                    
  预估毛利率: Estimated_Gross_Margin                     
  买家姓名: Buyer_Name                                   
  买家邮箱: Buyer_Email                                  
  买家留言: Buyer_Message                                
  收件人: Recipient                                      
  电话: Phone                                            
  国家/地区: Ship_Country                                
  省/州: Ship_State                                      
  城市: Ship_City                                        
  区/县: District                                        
  城镇: Town                                             
  邮编: Zip_Code                                         
  门牌号: House_Number                                   
  订单取消原因: Cancel_Reason                            
  退货/退款状态: Return_Refund_Status                    
  地址类型: Address_Type                                 
  公司名: Company_Name                                   
  地址行1: Address_Line_1                                
  地址行2: Address_Line_2                                
  地址行3: Address_Line_3                                
  用户名（买家）: Username_Buyer                         
  付款方式: Payment_Method                               
  付款方式（详情）: Payment_Method_Details                
  分期付款计划: Installment_Plan                         
  手续费: Handling_Fee         
  商品备注: Bundle_Deals_Indicator
  订单取消日期: Order_Cancel_Datetime
  佣金: Commission_Fee
                                       


# 指定字段的映射 (中文名称 -> 数据库字段名)

mappings:
  日期: Purchase_Datetime
  订单号: Order_ID
  大区: Region
  国家: Ship_Country
  原币种: Currency
  渠道: Fulfillment_Channel
  运营负责人: Product_Manager
  产品类目: Product_Category
  父ASIN/spu: Tags
  子ASIN/sku: Product_ID
  品名: Product_Name
  "69码": "69_Code"
  规格: Variation_Name
  访客: Session
  销量: Quantity
  订单件数: Number_Of_Pieces
  销售额: Total_Amount
  回款额: Products_Price_Paid_By_Buyer
  销售毛利: Estimated_Gross_Profit
  产品成本: Product_Cost
  销售净利: Net_Profit
  销售毛利率: Estimated_Gross_Margin
  净利率: Net_Margin_Rate
  返利: Rebate
  佣金费: Commission_Fee
  交易费: Transaction_Fee
  服务费: Service_Fee
  头程: First_Leg_Shipping_Cost
  出库费: Outbound_Cost_CNY
  运费: Shipping_Cost
  联盟营销: Affiliate_Marketing
  退货数量: Return_Quantity
  退货率: Return_Rate
  退货运费: Reverse_Shipping_Fee
  退货费用: Return_Fee
  广告花费: Advertising_Spend
  税费: Item_Tax